### ISSUE TITLE
【カード閲覧画面】内容の表示ができない

### ISSUE THREAD

**Issue by pimanaya** [No-preservatives-added/MemoCard#21]
画面遷移時に全カードリストの内容を更新するが、リストの更新が終わるまでに表示を行い、エラーが出る。（おそらく）
asyncが使えればいいのだが...

**Comment by nambatsu** [comment]
解決したのぢは？

**Comment by pimanaya** [comment]
最初にデフォルトデータを表示することで解決。
要改善かもだけど、解決はしている。
