### ISSUE TITLE
async-strageをreact-native-strageに変更

### ISSUE THREAD

**Issue by nambatsu** [No-preservatives-added/MemoCard#7]

**Comment by pimanaya** [comment]
https://kyokara.com/expo-asyncstorage-mac/
こっちの方が、今までの使い方と一緒だから良くない？

**Comment by nambatsu** [comment]
![image](https://user-images.githubusercontent.com/53079276/160286958-4d4323bd-73ea-4af8-afcf-e1d38685a878.png)
こう書いてあるけど使えるの？

**Comment by nambatsu** [comment]
まあ一旦こっちで試してみる。

**Comment by pimanaya** [comment]
https://reactnative.directory/?search=storage
![image](https://user-images.githubusercontent.com/41662342/160290108-85fe8442-b21a-42fd-bb27-e1c4c2d63380.png)
どうなんやろ

**Comment by pimanaya** [comment]
expo install @react-native-async-storage/async-storage
import AsyncStorage from "@react-native-async-storage/async-storage";
するだけで動いたのでこの件片付いたってことでいい？
